packages:
  - packages/*
  - playground
  - examples/*

overrides:
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@~0.2.5
  vite-plus: ~0.2.5
  vitest: 4.1.10
onlyBuiltDependencies:
  - esbuild
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
