packages:
  - packages/*
  - playground
  - examples/*

overrides:
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@~0.3.3
  vite-plus: ~0.3.3
  vitest: 4.1.11
onlyBuiltDependencies:
  - esbuild
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - harfbuzzjs@1.6.2
  - html-encoding-sniffer@7.0.0
  - jsdom@30.1.1
  - w3c-xmlserializer@6.0.0
