// Encode WASM binary as base64 TypeScript constant for sync init.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = resolve(__dirname, "../wasm/shuimo-noise/pkg/shuimo_noise_bg.wasm");
const outPath = resolve(__dirname, "../src/foundation/noise/wasm-noise-data.ts");

const buf = readFileSync(wasmPath);
const b64 = buf.toString("base64");

writeFileSync(outPath, `// Auto-generated by scripts/encode-wasm.mjs\nexport const WASM_NOISE_BASE64 = "${b64}";\n`);

console.log(`✅ Wrote ${buf.length} bytes WASM → ${b64.length} chars base64`);
