/**
 * Build-time script: extract glyph metrics from the seal script font (峄山碑篆体)
 * using opentype.js and generate a TypeScript data module.
 *
 * Usage: node --import tsx scripts/generate-font-metrics.mts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_PATH = resolve(__dirname, "../../../playground/src/assets/fonts/yishanbeizhuanti.ttf");
const OUTPUT_PATH = resolve(__dirname, "../src/drawing/stamp-font-metrics.ts");

// CJK Unicode ranges to include
const CJK_RANGES: [number, number][] = [
  [0x4e00, 0x9fff], // CJK Unified Ideographs
  [0x3400, 0x4dbf], // CJK Extension A
  [0x3000, 0x303f], // CJK Symbols and Punctuation
  [0xff00, 0xffef], // Fullwidth Forms
];

function isInCJKRange(codePoint: number): boolean {
  return CJK_RANGES.some(([start, end]) => codePoint >= start && codePoint <= end);
}

function main() {
  console.log(`Reading font: ${FONT_PATH}`);
  const fontBuffer = readFileSync(FONT_PATH);
  const font = opentype.parse(fontBuffer.buffer as ArrayBuffer);

  const unitsPerEm = font.unitsPerEm;
  const ascender = font.ascender / unitsPerEm;
  const descender = font.descender / unitsPerEm;

  console.log(`Font: ${font.names.fontFamily?.en || "unknown"}`);
  console.log(
    `unitsPerEm: ${unitsPerEm}, ascender: ${ascender.toFixed(4)}, descender: ${descender.toFixed(4)}`,
  );

  // Collect glyph metrics
  const glyphData: Record<string, { aw: number; h: number }> = {};
  let totalGlyphs = 0;
  let monoWidthCount = 0;
  let firstAdvanceWidth: number | null = null;

  for (let i = 0; i < font.glyphs.length; i++) {
    const glyph = font.glyphs.get(i);
    if (!glyph.unicode) continue;
    if (!isInCJKRange(glyph.unicode)) continue;

    const char = String.fromCodePoint(glyph.unicode);
    const aw = glyph.advanceWidth / unitsPerEm;
    const bbox = glyph.getBoundingBox();
    const h = (bbox.y2 - bbox.y1) / unitsPerEm;

    if (firstAdvanceWidth === null) firstAdvanceWidth = aw;
    if (Math.abs(aw - (firstAdvanceWidth ?? 0)) < 0.001) monoWidthCount++;

    glyphData[char] = { aw, h };
    totalGlyphs++;
  }

  console.log(`Total CJK glyphs found: ${totalGlyphs}`);
  console.log(`Monospaced advance width glyphs: ${monoWidthCount}/${totalGlyphs}`);

  // Check if font is monospaced (all CJK glyphs same advance width)
  const isMonospaced = monoWidthCount === totalGlyphs && firstAdvanceWidth !== null;
  const uniformAdvanceWidth = isMonospaced ? firstAdvanceWidth! : null;

  if (isMonospaced) {
    console.log(
      `Font is CJK-monospaced! Uniform advance width: ${uniformAdvanceWidth!.toFixed(4)}`,
    );
  }

  // Generate TypeScript output
  let output = `/** Auto-generated by scripts/generate-font-metrics.mts — DO NOT EDIT */\n\n`;
  output += `export interface FontMetrics {\n`;
  output += `  fontFamily: string\n`;
  output += `  unitsPerEm: number\n`;
  output += `  ascender: number\n`;
  output += `  descender: number\n`;
  output += `  uniformAdvanceWidth: number | null\n`;
  output += `  glyphs: Record<string, number>\n`;
  output += `}\n\n`;

  output += `export const YISHANBEIZHUANTI_METRICS: FontMetrics = {\n`;
  output += `  fontFamily: '峄山碑篆体',\n`;
  output += `  unitsPerEm: ${unitsPerEm},\n`;
  output += `  ascender: ${ascender},\n`;
  output += `  descender: ${descender},\n`;

  if (isMonospaced) {
    output += `  uniformAdvanceWidth: ${uniformAdvanceWidth},\n`;
    // Only store height per glyph since width is uniform
    output += `  glyphs: {\n`;
    const entries = Object.entries(glyphData);
    for (let i = 0; i < entries.length; i++) {
      const [char, { h }] = entries[i];
      const escaped = char === "'" ? "\\'" : char === "\\" ? "\\\\" : char;
      output += `    '${escaped}': ${parseFloat(h.toFixed(4))}${i < entries.length - 1 ? "," : ""}\n`;
    }
    output += `  },\n`;
  } else {
    output += `  uniformAdvanceWidth: null,\n`;
    // Store [advanceWidth, height] tuples
    // For non-monospaced, we use a different format
    output += `  /** For non-monospaced fonts, values encode advanceWidth * 10000 + height * 10000 — not used here */\n`;
    output += `  glyphs: {\n`;
    const entries = Object.entries(glyphData);
    for (let i = 0; i < entries.length; i++) {
      const [char, { h }] = entries[i];
      const escaped = char === "'" ? "\\'" : char === "\\" ? "\\\\" : char;
      output += `    '${escaped}': ${parseFloat(h.toFixed(4))}${i < entries.length - 1 ? "," : ""}\n`;
    }
    output += `  },\n`;
  }

  output += `} as const\n`;

  writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.log(`\nWritten to: ${OUTPUT_PATH}`);
  console.log(`Glyph entries: ${totalGlyphs}`);

  // Estimate file size
  const sizeKB = (Buffer.byteLength(output, "utf-8") / 1024).toFixed(1);
  console.log(`File size: ~${sizeKB} KB`);
}

main();
