/**
 * Build-time script: extract glyph metrics from the seal script font (峄山碑篆体)
 * using fontkit and generate a TypeScript data module.
 *
 * Usage: node --import tsx scripts/generate-font-metrics.mts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import * as fontkit from "fontkit";
import type { Font, FontCollection } from "fontkit";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_PATH = resolve(__dirname, "../../../playground/src/assets/fonts/yishanbeizhuanti.ttf");
const OUTPUT_PATH = resolve(__dirname, "../src/drawing/stamp-font-metrics.ts");

// CJK Unicode ranges to include
const CJK_RANGES: [number, number][] = [
  [0x4e00, 0x9fff], // CJK Unified Ideographs
  [0x3400, 0x4dbf], // CJK Extension A
  [0x3000, 0x303f], // CJK Symbols and Punctuation
  [0xff00, 0xffef], // Fullwidth Forms
];

function isInCJKRange(codePoint: number): boolean {
  return CJK_RANGES.some(([start, end]) => codePoint >= start && codePoint <= end);
}

function isCollection(obj: Font | FontCollection): obj is FontCollection {
  return Array.isArray((obj as FontCollection).fonts);
}

function main() {
  const fontBuffer = readFileSync(FONT_PATH);
  const parsed = fontkit.create(fontBuffer);
  const font = isCollection(parsed) ? parsed.fonts[0] : parsed;
  if (!font) throw new Error("font: failed to load");

  const unitsPerEm = font.unitsPerEm;
  const ascender = font.ascent / unitsPerEm;
  const descender = font.descent / unitsPerEm;

  // Collect glyph metrics
  const glyphData: Record<string, { aw: number; h: number }> = {};
  let totalGlyphs = 0;
  let monoWidthCount = 0;
  let firstAdvanceWidth: number | null = null;

  for (const codePoint of font.characterSet) {
    if (!isInCJKRange(codePoint)) continue;
    const glyph = font.glyphForCodePoint(codePoint);
    if (!glyph) continue;

    const char = String.fromCodePoint(codePoint);
    const aw = glyph.advanceWidth / unitsPerEm;
    const bbox = glyph.bbox;
    const h = (bbox.maxY - bbox.minY) / unitsPerEm;

    if (firstAdvanceWidth === null) firstAdvanceWidth = aw;
    if (Math.abs(aw - (firstAdvanceWidth ?? 0)) < 0.001) monoWidthCount++;

    glyphData[char] = { aw, h };
    totalGlyphs++;
  }

  // Check if font is monospaced (all CJK glyphs same advance width)
  const isMonospaced = monoWidthCount === totalGlyphs && firstAdvanceWidth !== null;
  const uniformAdvanceWidth = isMonospaced ? firstAdvanceWidth! : null;

  // Generate TypeScript output
  let output = `/** Auto-generated by scripts/generate-font-metrics.mts — DO NOT EDIT */\n\n`;
  output += `export interface FontMetrics {\n`;
  output += `  fontFamily: string\n`;
  output += `  unitsPerEm: number\n`;
  output += `  ascender: number\n`;
  output += `  descender: number\n`;
  output += `  uniformAdvanceWidth: number | null\n`;
  output += `  glyphs: Record<string, number>\n`;
  output += `}\n\n`;

  output += `export const YISHANBEIZHUANTI_METRICS: FontMetrics = {\n`;
  output += `  fontFamily: '峄山碑篆体',\n`;
  output += `  unitsPerEm: ${unitsPerEm},\n`;
  output += `  ascender: ${ascender},\n`;
  output += `  descender: ${descender},\n`;

  if (isMonospaced) {
    output += `  uniformAdvanceWidth: ${uniformAdvanceWidth},\n`;
    // Only store height per glyph since width is uniform
    output += `  glyphs: {\n`;
    const entries = Object.entries(glyphData);
    for (let i = 0; i < entries.length; i++) {
      const [char, { h }] = entries[i];
      const escaped = char === "'" ? "\\'" : char === "\\" ? "\\\\" : char;
      output += `    '${escaped}': ${parseFloat(h.toFixed(4))}${i < entries.length - 1 ? "," : ""}\n`;
    }
    output += `  },\n`;
  } else {
    output += `  uniformAdvanceWidth: null,\n`;
    // Store [advanceWidth, height] tuples
    // For non-monospaced, we use a different format
    output += `  /** For non-monospaced fonts, values encode advanceWidth * 10000 + height * 10000 — not used here */\n`;
    output += `  glyphs: {\n`;
    const entries = Object.entries(glyphData);
    for (let i = 0; i < entries.length; i++) {
      const [char, { h }] = entries[i];
      const escaped = char === "'" ? "\\'" : char === "\\" ? "\\\\" : char;
      output += `    '${escaped}': ${parseFloat(h.toFixed(4))}${i < entries.length - 1 ? "," : ""}\n`;
    }
    output += `  },\n`;
  }

  output += `} as const\n`;

  writeFileSync(OUTPUT_PATH, output, "utf-8");
}

main();
